name: Publish Maven

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Print GH_ACTOR
        env:
          GH_ACTOR: ${{ env.GH_ACTOR }}
        run: echo "GH_ACTOR=$GH_ACTOR"
      - name: create .env file
        env:
            GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
            GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
            GH_ACTOR: ${{ env.GH_ACTOR }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "gmail_username=$GMAIL_USERNAME" >> .env 
          echo "gmail_app_password=$GMAIL_APP_PASSWORD" >> .env
          echo "GH_ACTOR=$GH_ACTOR" >> .env
          echo "GH_TOKEN=$GH_TOKEN" >> .env
      - name: Publish
        run: mvn deploy